# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

# workflow triggered on push to master branch or pull request vs master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]

    steps:
    # checkout this repo
    - uses: actions/checkout@v2
    # setup python 3.7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # install required python dependencies of package
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas nbconvert matplotlib beautifulsoup4 requests mistune
    # upload int token hidden behind secret for testing of publishing to Medium
    - name: upload integration token
      shell: bash
      env:
        TOKEN: ${{ secrets.INTEGRATION_TOKEN }}
      run: mkdir $HOME/.jupyter_to_medium && echo "$TOKEN" >> $HOME/.jupyter_to_medium/integration_token
      # run pytest to check code still works
    - name: Test with pytest
      run: pytest
